#!/bin/bash

echo "Deploying Typo3..."
build_config

cd $OPENSHIFT_DATA_DIR
ln -sf $OPENSHIFT_REPO_DIR/typo3
mkdir -p www

cd $OPENSHIFT_REPO_DIR/.openshift/chron/hourly
chmod +x hourly-task

cd $OPENSHIFT_REPO_DIR/typo3
composer install --no-dev

cd $OPENSHIFT_REPO_DIR
ln -sf $OPENSHIFT_DATA_DIR/www

cd $OPENSHIFT_DATA_DIR/www

ln -sf $OPENSHIFT_REPO_DIR/typo3 typo3_src
ln -sf typo3_src/index.php
ln -sf typo3_src/typo3

if [ ! -f typo3conf/LocalConfiguration.php ]; then
    echo "Typo3 config not found!"
    touch FIRST_INSTALL
fi
