#!/bin/bash

echo "Deploying Typo3..."
build_config

# Uncomment the following line to use Composer and automatically install dependencies on deploy.
#

cd app-root/data
mkdir -p fileadmin
mkdir -p typo3conf
mkdir -p typo3temp
mkdir -p uploads


cd $OPENSHIFT_REPO_DIR/.openshift/chron/hourly
chmod +x hourly-task


cd $OPENSHIFT_REPO_DIR/typo3; composer install --no-dev
cd $OPENSHIFT_REPO_DIR/www

ln -s ../typo3 typo3_src
ln -s typo3_src/index.php
ln -s typo3_src/typo3

ln -s ../../data/fileadmin
ln -s ../../data/typo3conf
ln -s ../../data/typo3temp
ln -s ../../data/uploads

if [ ! -f typo3conf/LocalConfiguration.php ]; then
    echo "Typo3 config not found!"
    touch FIRST_INSTALL
fi
